server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/SUSTechNote?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/SUSTechNote?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          temp:
            use_jdbc_metadata_defaults: false
