server:
  port: 8088
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SUSTechNote?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

  mail:
#    host: smtp.sustech.edu.cn
#    port: 465
#    username: 12011118@mail.sustech.edu.cn
#    password: CHen20020825
    host: smtp.qq.com
    port: 465
    username: 392546005@qq.com
    password: gbmopzaxunsqbijh
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  data:
    redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 200
      password:
      database: 0

